sudo: false

language: python

python:
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements/test.txt

before_script:
  - echo "Waiting 60 seconds for new deployment of the branch"
  - sleep 60s

script:
  - pytest

notifications:
  email: false
